"""add role column to users

Revision ID: a1b30b77d867
Revises: 4bed89c30b4f
Create Date: 2026-07-14 15:30:36.397132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b30b77d867'
down_revision: Union[str, Sequence[str], None] = '4bed89c30b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('role', sa.String(length=50), nullable=False, server_default='viewer'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
