"""add extracted_text column to documents

Revision ID: df65101a496a
Revises: a82fef98d4e3
Create Date: 2026-07-15 10:26:34.506105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df65101a496a'
down_revision: Union[str, Sequence[str], None] = 'a82fef98d4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
